### ISSUE TITLE
Task 14 Publishing extensions

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-devitpro-pb#630]
I consistently get this error:
Trying to publish the APIV1.app (Name: _Exclude_APIV1_ Publisher: Microsoft Version: 1.0.32335.0)
Publish-NAVApp : Extension compilation failed
src/pages/PAG20004.AutUsers.al(63,35): error AL0320: The referenced page 'Automation User Permission' must specify a 'SourceTable'.

Is this a known issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30fdac4a-82ce-2bce-6ebe-d40241f4b715
* Version Independent ID: ee365d3f-f0df-c3e2-7a87-833a84dc9496
* Content: [Upgrading the Database - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-data)
* Content Source: [dev-itpro/upgrade/Upgrading-the-Data.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/Upgrading-the-Data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by GreatScott000** [comment]
This is an upgrade of a Demo Database October 2018 CU03 to Spring 2019 CU01.

**Comment by AR101** [comment]
We are using the Spring Release 2019 CU01 for Germany (14.01 NAVDE) and getting the same error and cant get the following extensions to work correctly:
- APIV1.app
- PayPalPaymentsStandard.app

It is worth mentioning, that we are working with a hybrid environment unfortunately.
Meaning we have an ISV Solution integrated using C/AL and install the Extensions Microsoft provides afterwards.
At first we had problems, as we modified pages that are used in the tests, but I could fix that by restoring the original Fields that where missing and generating symbols. The mentioned error remained, though.

So I also started to fiddle around with the source of **APIV1** and changed the manifest to use **"14.0.0.0 "** instead of **"13.0.0.0"** for test.
I could build the source then, but deployment failed with the same error.

My guess is, that generating the application symbols somehow messes with the symbols provided by the **TEST** and **SYSTEM** symbol packages.
But I have no means of further debugging.

I can provide input or clarification on our problem, if needed.
But right now, I am going to pause working on this issue.
I am just happy, that our customer does not need the mentioned extensions (yet ...)

I hope we can resolve the issue though, so we can install the Extensions anyways.

**Comment by AndersLarsenMicrosoft** [comment]
I just investigated the issue with installing APIV1 on a technical upgraded database. To get this to work it is required to manual import page 5442 and 5546 from the lasted baseapp to get this work (depending on how old the baseapp is in the database)

**Comment by GreatScott000** [comment]
I am working with the standard Cronus Demo Database from the October 2018 RTM release.  Both of the pages mentioned already exist (5442 and 5546).  What do you mean by "manually import".  They exist in the Spring 2019 CU01 release as the same versions.

**Comment by AR101** [comment]
Thanks for the feedback so far.

I checked the objects and could find **Page 5442**.
But **Page 5546** is missing completely in Business Central on Premise 14.1

It is not in the development container, teh objects on the installation DVD or the DemoDatabase BAK SQL Backup.

Currently downloading the new CU for August, I assume the missing page is in there and the issues are resolved with upgrading to the newer version.

I will try one of these days, but probably not before next week.

**Comment by GreatScott000** [comment]
@AR101 Are you sure you mean Page 5**5**46 and not 5**4**46.  Page 5546 does not exist in BC13.3 either.

BC13.3:
> Type	ID	Name	Compiled	Modified	Version List	Date	Time
> 8	5442	Automation User Group Member	Yes	No	NAVW113.00	19/09/18	12:00:00
> 8	5446	Automation User Permission	Yes	No	NAVW113.00	19/09/18	12:00:00

BC14.1
> Type	ID	Name	Compiled	Modified	Version List	Date	Time
> 8	5442	Automation User Group Member	Yes	No	NAVW113.00	19/09/18	12:00:00
> 8	5446	Automation User Permission	Yes	No	NAVW113.00	19/09/18	12:00:00

BC14.2
> Type	ID	Name	Compiled	Modified	Version List	Date	Time
> 8	5442	Automation User Group Member	Yes	No	NAVW113.00	19/09/18	12:00:00
> 8	5446	Automation User Permission	Yes	No	NAVW113.00	19/09/18	12:00:00
>

**Comment by AndersLarsenMicrosoft** [comment]
Yes you are correct sorry for the typo. I should have typed 5442 & 5446
/Anders

**Comment by update-jeremy** [comment]
Can confirm this is still an issue in CU1 of the APIV1.APP file.

**Comment by Ajef** [comment]
We're having this issue with BC140 CU02 on prem and the APIV1.app.

**Comment by GreatScott000** [comment]
Any update on this?

**Comment by AndersLarsenMicrosoft** [comment]
Sorry this skip my radar. I will try to repro on Update 26 = 14.1 durring today or monday

**Comment by update-jeremy** [comment]
Snälla!  We've cancelled 3 API projects because we can't install the API.  Even if we can work around it, how can we trust the rest of it?

**Comment by AndersLarsenMicrosoft** [comment]
Are your repro steps
Take a clean 14.1 
Install the API using PowerShell?

**Comment by Crunch77** [comment]
BC14cu00 to BC14cu02 we experience this issue with on prem and the APIV1.app.

**Comment by AndersLarsenMicrosoft** [comment]
So it appears to repro on 14, 14.1 and 14.2. I am in the process of creating a 14.1 environment.

**Comment by AndersLarsenMicrosoft** [comment]
on 14.x the API v1 work of the page

**Comment by AndersLarsenMicrosoft** [comment]
i verified this by enabling the API  and Odata in the mancli and then ran ...NAV/api/v1.0/companies(c2c81e3d-9774-49c9-b1e9-f6a15dd8ee09)/customers. Is your problem a technical upgrade database?

**Comment by GreatScott000** [comment]
The original problem occurred following the upgrade instructions.  Get to step 14 and reinstall base apps an this occurs.

> Trying to publish the APIV1.app (Name: Exclude_APIV1 Publisher: Microsoft Version: 1.0.32335.0)
> Publish-NAVApp : Extension compilation failed
> src/pages/PAG20004.AutUsers.al(63,35): error AL0320: The referenced page 'Automation User Permission' must specify a 'SourceTable'.

The error cannot be resolved by any means I have found.  I am not trying access ODATA or the API, I am trying to reinstall the base apps.  This is a BC13 CU3 demo database being upgraded to BC14 CU1.  No modified objects, no 3rd party apps.  Plain, stock, default Cronus database.

**Comment by GreatScott000** [comment]
Just thought I would try it with the BC14 CU2 (July cumulative update release).

Still getting this error:

> Publish-NAVApp : Extension compilation failed
> src/pages/PAG20004.AutUsers.al(63,35): error AL0320: The referenced page 'Automation User Permission' must specify a 'SourceTable'.
> src/pages/PAG20039.Attachments.al(55,23): warning AL0273: The name 'content' is an Area type. Using an Area type name may limit extensibility.
> src/pages/PAG20040.GLEntryAttachments.al(54,23): warning AL0273: The name 'content' is an Area type. Using an Area type name may limit extensibility.
> src/pages/PAG20006.AutExtensionUpload.al(22,23): warning AL0273: The name 'content' is an Area type. Using an Area type name may limit extensibility.
> At line:54 char:9
>          Publish-NAVApp -ServerInstance $ServerInstance -Path $BaseApp ...
>          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
>      FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC140_TEMP/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp
> 

Also getting this error with the PayPal Payments Standard extension (I was getting this before but it is not relevant to the client so I ignored it.

> Publish-NAVApp : Extension compilation failed
> src/tables/TAB1070.al(200,73): error AL0133: Argument 1: cannot convert from 'Record "Webhook Subscription"' to 'var __MissingTypeSymbol__'
> src/tables/TAB1070.al(229,73): error AL0133: Argument 1: cannot convert from 'Record "Webhook Subscription"' to 'var __MissingTypeSymbol__'
> At line:58 char:13
>              Publish-NAVApp -ServerInstance $ServerInstance -Path $Bas ...
>              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
>      FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC140_TEMP/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp
>

**Comment by peterlinnet** [comment]
Any news on this?

I have the excact same issue as @GreatScott000 posted 9 days ago.

My environment is a completely clean NAV 2018 CU3 App database upgraded to BC140.
APIV1.app install fails with mentioned error message
PayPalPaymentsStandard.app install fails with mentioned error message

Any info is much appreciated

**Comment by AndersLarsenMicrosoft** [comment]
We have created an internal bug and will return with our findings

**Comment by peterlinnet** [comment]
Just tried with the BC140 CU4 release.
Same issue.

**Comment by GreatScott000** [comment]
@AndersLarsenMicrosoft anything further on this.  I opened the original issue 12 July.  It was marked as "Investigating" on 30 July.  You said you created an internal bug for this on 13 September.  When can we expect an update.  This is holding up a number of upgrades.

**Comment by dcenic** [comment]
@peterlinnet @GreatScott000 @Crunch77 @update-jeremy @AR101 please check whether the NST instance has the setting "Enable loading application symbol references at server startup" (EnableSymbolLoadingAtServerStartup) set to true. If not, set it to true in the NST CustomSettings.config, restart the NST instance, and retry to publish the extensions that fail.

I'm checking this, because documentation page:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/converting-a-database
mentions that you should set this setting to true before publishing extensions
whereas the page that is referenced in this GitHub issue:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-data
doesn't mention this server setting.

**Comment by GreatScott000** [comment]
@dcenic I will review this and advise as soon as possible (the next day or so)

**Comment by peterlinnet** [comment]
@dcenic I just double chacked that setting (naturally it's enabled or we would have a hard time developing other extensions against the environment) tried it on both a clean BC140 CU4 app database and one with customized objects and other extensions installed. Both fail with same error message.

**Comment by update-jeremy** [comment]
Likewise, was just finishing testing it.  It has no effect.

**Comment by Crunch77** [comment]
"Enable loading application symbol references at server startup" is already set.

**Comment by dcenic** [comment]
When you run "finsql.exe command=generatesymbolreference, ServerName=<DatabaseServerName>\<DatabaseInstance>, Database="<MyDatabaseName>, filter="Object ID=1..129999"
 command, the symbols are written in the Object Metadata table in the database. However, if you have static Application extensions that are published in your upgraded database, the compiler will use the symbols from those extensions, instead of those that you generated in Object Metadata.
The workaround, therefore, could be to unpublish the static Application extensions. You can to this by running:
1. Get-NavAppInfo -ServerInstance <YourInstance> -SymbolsOnly
    This will show you a list of extensions that are published with symbols only.
2. Identify the extensions with the name "Application" (you will need their version number too), and unpublish them 
    Unpublish-NAVApp -ServerInstance <YourInstance> -Name "Application" -Version <ExtensionVersion>
After this, when publishing a new app, the compiler should use the symbols that were written in Object Metadata when you ran "finsql.exe command=generatesymbolreference, ServerName=<DatabaseServerName>\<DatabaseInstance>, Database="<MyDatabaseName>, filter="Object ID=1..129999""

**Comment by peterlinnet** [comment]
That would make more sense, but those symbols are not installed on our server. Only System and Test.
`ServerInstance                      AppId                                Name   Publisher Version      ExtensionType  Scope
--------------                      -----                                ----   --------- -------      -------------  -----
MicrosoftDynamicsNavServer$BC140Exc 8874ed3a-0643-4247-9ced-7a7002f7135d System Microsoft 14.0.35916.0     ModernDev Global
MicrosoftDynamicsNavServer$BC140Exc b4380b58-b69c-4698-8bf3-b5a5d5dde7ab Test   Microsoft 14.5.35970.0     ModernDev Global
`

**Comment by GreatScott000** [comment]
@dcenic Same results as before after having reviewed your suggestions.  This still needs to be resolved.

**Comment by dcenic** [comment]
@GreatScott000 Judging by the error, it looks like system table "Access Control" is not in the System symbols. However, I have checked the System.app file, and the SymbolReferences.json inside it, shows that the Access Control table is included. At this point, I need to ask to set up a call, so we can try and debug the issue on your environment. Can you please share your e-mail address and I will set up a Teams call for Monday, if that is OK with you?

**Comment by GreatScott000** [comment]
@dcenic My address is todd.scott@evolveims.com.  Tuesday would be a better day for a meeting but I can make Monday work if I must.

**Comment by GreatScott000** [comment]
Follow these instructions as strictly and as far as I know, exactly, it is NOT POSSIBLE to upgrade from BC13 to BC14.  Please provide the correct instructions.

**Comment by GreatScott000** [comment]
I will happily meet with @dcenic or any other MS representative and go through this process step-by-step.  It has been MONTHS that I have been trying to get this resolved.

**Comment by peterlinnet** [comment]
I don't suppose you had the meeting 4 weeks ago then? Do we then conclude, that it's not possible to upgrade (neither from BC13 nor NAV2018) to BC14 and hope to be able to install the API / PayPal extensions?

**Comment by GreatScott000** [comment]
Yes I had the meeting and demonstrated the problem.  They went away and came back with the a solution to install the Microsoft Application APP from an AL project. That fixed that problem but is not in the instructions and seems to be very Kludge like.  The GenerateSymbolReference function is supposed to do that so why would I need to creat an AL app, download symbols and install that APP?

To top it off I still can not install APIV1.APP because now it get a message that our license does not allow me to install it.  I have tried our license and a license from another partner.  

They tell me I have open a support case to get figured out.  Some times it feels like the monkeys are running the circus.

**Comment by peterlinnet** [comment]
Hmm I guess then that the 140 Cronus Database comes with the Application APP preinstalled, but if you upgrade your application database from a previous version (or create a fresh one from the development environment for use as an application database in a multitenant setup) it will not contain the nescessary symbols.

I guess I can live with that given the fact that we already have the "Task 12: (Multitenant mode only) Publish extensions", for the System and Test symbols. Only the Application symbols are not present on the install-media (at least I can't find them) so it's not possible for me to test whether I'm able to fix the issue that way...

@dcenic: are we getting closer?

**Comment by GreatScott000** [comment]
@peterlinnet you can get the Application symbols by creating a default AL project and downloading the systems for it.  One of them will, of course, be the Microsoft Application <build no>.APP.  You can use this to install into your upgrade.

I continue to work with @dcenic to get the process resolved.  I have been informed by a colleague of his that there were some bug fixes that may correct the problem.  These are available in 14.5.  I will be testing this in the next day or so.

**Comment by dcenic** [comment]
@peterlinnet The process that @GreatScott000 shared in the previous post, will get you over the hurdle of compiling APIV1.
However, a license issue still makes the publishing fail. This is a bug, because the licenses that we generate for partners do not include ID ranges for test objects, and the APIV1 that we shipped for Business Central 14.x does contain test objects.
We have taken out the test objects to a separate extension for Business Central 15.x. We need to backport that fix to 14.x as well. In the meanwhile, you can use this as a workaround for the license issue:
1.	You have access to the source code of APIV1 on the DVD  - Extensions\APIV1.Source.zip
2.	Unzip the folder, open it in VS Code, and take out the test objects
3.	Build the app without the test objects, and publish it.

**Comment by vytjak** [comment]
We have the same issue with installing PayPal extension on BC14.00 (RTM) upgraded from NAV 2017.
So, if I understand correctly, to solve it we need to:
  1) create an AL project against a fresh BC 14,00 DB
  2) get the Application symbols 
  3) install that System app file on the database being upgraded (i.e. replace the System app installed from the product installation media)
  4) Install PayPal extension

**Comment by vytjak** [comment]
By the way, was this solved in later CUs for BC14.x on premises?

**Comment by GreatScott000** [comment]
@vytjak it is the Microsoft Application <versionno>.app file that you publishing.  This is not the System.App.  Otherwise you procedure is correct.

**Comment by GreatScott000** [comment]
@vytjak I am told that there were issues that were corrected in 14.5 (14.7.???).  I have not been able to test this.

**Comment by GreatScott000** [comment]
Hi All
So the solution to publish the APIV1 app from VS Code works.  The process is:

unzip the APIV1.APP
remove the Test App from the APIV1.APP 
in the `app.json`, add these settings;
```
    "idRange": {"from": 20000, "to": 20050},
    "features": ["TranslationFile"],
    "runtime": "3.0"
```
in the .vscode folder, edit the settings.json and remove these lines
```
        "${PerTenantExtensionCop}",
    "al.ruleSetPath": "../firstparty.ruleset.json",
```
the PTE analyzer gives errors about the ID range having to be between 50000 and 99999
the `al.ruleSetPath` is not provide.   I assume it suppresses on or more PTE warnings and errors like the one about the ID Range.
delete the `test` folder
define an appropriate `launch.json`
download symbols
publish the app.

The process allows me to publish the app successfully via VS Code, I assume it will work via PS but I have not tried yet.

If you are having issues with "Your program license does not allow you to publish" type errors with other extensions (PayPal?) then the same process should work.

@dcenic tells me that the test objects have been moved to a separate extension in BC15 and they will work on splitting them for BC14.

**Comment by GreatScott000** [comment]
@dcenic I don't see how having a separate Test app helps me if I wanted to use the Test objects,  I would still not be able to publish the app, even if it is separate.   How could I test this?  

Would I have to renumber the objects and publish it manually or have you resolved this in some other way?

**Comment by dcenic** [comment]
@GreatScott000 Yes, you would need to renumber the test objects and publish them manually, if you want to run them.

**Comment by JesperSchulz** [comment]
I must admit I haven't read though all the comments in this thread, but I'd like to conclude on the issue nonetheless :-) The problem we had, is that the tests in the APIV1 extension were outside of the permitted test range, which is 130.000 - 149.999. The tests in that extension where in range 150.XXX, which isn't open in any partner or developer license outside of Microsoft. We will re-ID the tests to be within the permitted range, which should make this issue disappear.
As a mitigation, you can delete the tests from the app and you will be able to publish.

**Comment by jswymer** [comment]
Hello, Thanks all for the comments! We will close this issue for now, but if you have more feedback, feel free to comment, and we will reopen the issue as needed.

**Comment by JoshC94** [comment]
Hi all, just in case anyone finds it helpful:

I had the same issue on BC14.x
As I did not want to modify / recompile the app, I went by spinning up a docker container for the version I was working on, obtained the installed APIV1 app as a runtime package (Get-NAVAppRuntimePackage Cmdlet) and installed it on the server-in-question.
So basically just 2 commands to fix the license issue (by precompiling) and no need to tamper with the app.
